# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Loman Labs
tagline:          'Research group at the University of Birmingham'
description:      'Research group at the University of Birmingham, fusing cutting-edge sequencing with microbial genomics.'
url:              http://nickloman.github.io/
baseurl:          /

author:
  name:           'Nick Loman'
  url:            https://nickloman.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
